{% set name = "django-approval" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-approval-{{ version }}.tar.gz
  sha256: 7b15074ed9d16039cd2f99fd87d4301ba8a9a67fdfebca342845af7494af76da

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=61.0
    - pip
  run:
    - python >=3.9
    - django >=3.2
    - django-annoying

test:
  imports:
    - approval
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/artscoop/django-approval
  summary: Easily moderate any content in Django before it's visible to the public.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
